image: 'node'

stages:
  - prepare
  - build
  - deploy

include:
  - local: kube.gitlab-ci.yml

prepare tools:
  stage: prepare
  image: alpine
  script:
    - apk add --no-cache git 
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/instalitre/ci-workflow.git ci-tools
  artifacts:
    paths:
      - ci-tools/

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - cat ci-tools/templates/hapi.Dockerfile.tpl > hapi.Dockerfile;
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/hapi.Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

cache:
  paths:
    - .m2/
