apiVersion: apps/v1
kind: Deployment
metadata:
  name: _APP_NAME_
  labels:
    app: _APP_NAME_
spec:
  replicas: 1
  selector:
    matchLabels:
      app: _APP_NAME_
  
  # Pod template
  template:
    metadata:
      labels:
        app: _APP_NAME_
    spec:
      containers:
        - name: test
          image: _REGISTRY_IMAGE_:_VERSION_
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: SENTRY_DSN
            value: _SENTRY_DSN_
          - name: DATABASE_URL
            value: _DATABASE_URL_
          - name: PORT
            value: "3000"
      imagePullSecrets:
        - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: _APP_NAME_
  labels:
    app: _APP_NAME_
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
      app: _APP_NAME_
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: _APP_NAME_
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.instalitre.social
      http:
        paths:
          - path: /
            backend:
              serviceName: _APP_NAME_
              servicePort: 8080
